NODE_NAMES = ['R2-D2', 'Chewbacca', 'C-3Po', 'Luke', 'Darth Vader', 'Camie',
               'Biggs', 'Leia', 'Beru', 'Owen', 'Obi-Wan', 'Motti', 'Tarkin',
               'Han', 'Greedo', 'Jabba', 'Dodonna', 'Gold Leader', 'Wedge',
               'Red Leader', 'Red Ten', 'Gold Five']
EDGES = [('Chewbacca', 'R2-D2'), ('C-3Po', 'R2-D2'), ('Beru', 'R2-D2'),
         ('Luke', 'R2-D2'), ('Owen', 'R2-D2'), ('Obi-Wan', 'R2-D2'),
         ('Leia', 'R2-D2'), ('Biggs', 'R2-D2'), ('Han', 'R2-D2'),
         ('Chewbacca', 'Obi-Wan'), ('C-3Po', 'Chewbacca'),
         ('Chewbacca', 'Luke'), ('Chewbacca', 'Han'), ('Chewbacca', 'Leia'),
         ('Camie', 'Luke'), ('Biggs', 'Camie'), ('Biggs', 'Luke'),
         ('Darth Vader', 'Leia'), ('Beru', 'Luke'), ('Beru', 'Owen'),
         ('Beru', 'C-3Po'), ('Luke', 'Owen'), ('C-3Po', 'Luke'),
         ('C-3Po', 'Owen'), ('C-3Po', 'Leia'), ('Leia', 'Luke'),
         ('Beru', 'Leia'), ('Luke', 'Obi-Wan'), ('C-3Po', 'Obi-Wan'),
         ('Leia', 'Obi-Wan'), ('Motti', 'Tarkin'), ('Darth Vader', 'Motti'),
         ('Darth Vader', 'Tarkin'), ('Han', 'Obi-Wan'), ('Han', 'Luke'),
         ('Greedo', 'Han'), ('Han', 'Jabba'), ('C-3Po', 'Han'),
         ('Leia', 'Motti'), ('Leia', 'Tarkin'), ('Han', 'Leia'),
         ('Darth Vader', 'Obi-Wan'), ('Dodonna', 'Gold Leader'),
         ('Dodonna', 'Wedge'), ('Dodonna', 'Luke'), ('Gold Leader', 'Wedge'),
         ('Gold Leader', 'Luke'), ('Luke', 'Wedge'), ('Biggs', 'Leia'),
         ('Leia', 'Red Leader'), ('Luke', 'Red Leader'),
         ('Biggs', 'Red Leader'), ('Biggs', 'C-3Po'), ('C-3Po', 'Red Leader'),
         ('Red Leader', 'Wedge'), ('Gold Leader', 'Red Leader'),
         ('Biggs', 'Wedge'), ('Red Leader', 'Red Ten'),
         ('Biggs', 'Gold Leader'), ('Luke', 'Red Ten')]
